export const animalSchema = {
  creator: '',
  _id: '',
  uuid: '',
  brinco: '',
  brincoDaMae: '',
  dadosCompra: {
    comprado: false,
    dtCompra: '',
    valorCompra: '',
    vendedor: '',
  },
  dadosObservacao: {
    animalObservado: false,
    motivo: '',
  },
  dadosCruzamentos: [],
  dadosVacinas: [],
  dadosMorte: {
    morreu: false,
    dtMorte: '',
    causaMorte: '',
  },
  dtNascimento: '',
  dadosVenda: {
    vendida: false,
    valorVenda: '',
    comprador: '',
    dtVenda: '',
  },
  estadaCurral: [],
  historico: [],
  imagem_url: '',
  imgPublicId:'',
  noCurral: false,
  nome: '',
  pasto: 'sem pasto definido',
  pesagem: [],
  producaoLeite: [],
  sexo: '',
  lote: 'sem lote definido',
  dadosServidor: {
    colecao: 'cow',
    relacao: 'propriedade',
    referencia: 'rebanho',
    populaveis: [
      'dadosCruzamentos',
      'estadaCurral',
      'pesagem',
      'historico',
      'producaoLeite',
      'dadosVacinas',
    ],
    lastUpdate: '',
    deletado: false,
  },
};
