export const animalSchema = {
  creator: "",
  _id: "",
  brinco: "",
  brincoDaMae: "",
  dadosCompra: {
    comprado: false,
    dtCompra: "",
    valorCompra: "",
    vendedor: "",
  },
  dadosCruzamentos: [],
  dadosMorte: {
    morreu: false,
    dtMorte: "",
    causaMorte: "",
  },
  dtNascimento: "",
  dadosVenda: {
    vendida: false,
    valorVenda: "",
    comprador: "",
    dtVenda: "",
  },
  estadaCurral: [],
  historico: [],
  imagem_url: "https://pngimg.com/uploads/cow/cow_PNG50576.png",
  noCurral: false,
  nome: "",
  pasto: "sem pasto definido",
  pesagem: [],
  producaoLeite: [],
  sexo: "",
  dadosServidor: {
    colecao: "cow",
    relacao: "propriedade",
    referencia: "rebanho",
    lastUpdate: "",
    deletado: false,
  },
};
